fmean > mean
fmean no longer around statistics module 3.7, causing:
`ImportError: cannot import name 'fmean' from 'statistics' (/usr/lib64/python3.7/statistics.py)`